<?php

// NAVIGATION
define("_FIL","Newsfeed");
define("_FILOF","Newsfeed of ");
define("_FAV","Favorite");
define("_MYFAV","My favourites");
define("_INSCRIPTION","Sign in");
define("_CONNEXION","Login");
define("_DECONNEXION","Logout");

//PRESENTATION PAGE 1
define("_PRESENTATION","Introduction");
define("_TEXTEPRESENTATION","Mews is a site that allows you to have in your news feed the latest magazine covers and the latest news.
           <br/> Mews was developed by the MTeam international team.
           9 young people passionate about the web and the news.
           Graphic designers, web developers and communicators work together to offer you a quality service.
           Dynamism, creativity and quality are at the heart of our project!");
define("_DESCRIPTIONUN","Real time news");
define("_TEXTEDESCRIPTIONUN","No more searching for news on different sites
With Mews you can follow news in real time and anywhere in the world. Similarly, a simple search can help you find the article you are looking for.");
define("_DESCRIPTIONDEUX","Customizing the news feed");
define("_TEXTEDESCRIPTIONDEUX","Are you tired of seeing information that is not useful to you? Thanks to the settings you can choose the topics that interest you in order to have only this information on your newsfeed.
");
define("_DESCRIPTIONTROIS","The most popular articles");
define("_TEXTEDESCRIPTIONTROIS","Thanks to the favorite tool you can see the information put forward by different users, it will allow you to see the most trendy news!");


define("_LEGENDVIDEO","The purpose of our video is to promote our website, make it visible to the general public. In this video we explain that we live in a world filled with information and that most of the information we consult does not interest us that's why the Mews project comes alive with this website you can choose the topics that interest you in order to have only information of the subjects which interest us.");
define("_REVUE","Newspaper");
define("_TEXTEREVUE","Today is March 8, 2018, the International Women's Rights Day. This is an opportunity for us, editors of Mews, to make a quick world tour.");
define("_LIRESUITE","Read more (download PDF)");


// REUTILISABLE
define("_ANNEXE","Attachments");
define("_BOOFOFSPEC","Book of specifications");
define("_CHARTE","Graphical charter");
define("_SOCIAL","Social networks");
define("_LINK","Link");
define("_ABOUT","About");
define("_FAQ","FAQ");
define("_MENTION","Legal Notice");
define("_USE","Terms of Service");
define("_PRENOM","FIRSTNAME");
define("_NOM","LASTNAME");
define("_DATENAISSANCE","BIRTH DATE");
define("_SEXE","Gender");
define("_FEMME","Wife");
define("_HOMME","Man");
define("_MAIL","MAIL ADDRESS");
define("_CMAIL","Confirm email address");
define("_MDP","PASSWORD");
define("_CMDP","Confirm password");
define("_CINSCRIPTION","Register");
define("_FMDP","(Forgot your password)");
define("_CCONEXION","Connection");
define("_PARAM","Settings");
define("_LISTFLUX","stream list");
define("_MERCI","Thank you");
define("_KWORD","Keywords");
define("_SKWORD","Keywords (separated by commas)");
define("_TREND","Top articles");
define("_VALIDATE","Validate");


// APROPOS

define("_TEXTEABOUT","Created in 2018, Mews is a platform specialized in information. Every day we choose the best information on all news topics: sports, business, science, people and more!

It's time to revolutionize the world of information, with Mews, you choose your sources and your subjects.

On Mews, you are at the center of the information!");

define("_QUI","Who are we ?");
define("_TEXTEQUI","Mews was developed by the international team MTeam. 9 young people passionate about the web and the news. Graphic designers, Web developers and communicators work together to offer you a quality service.
Dynamism, creativity and quality are at the heart of our project!");

//FAQ
define("_QMEWS","What is Mews?");
define("_TEXTFAQ","<p style = 'text-align: justify'> Mews is an information platform created in 2018. It brings together a large number of articles on all current topics. With Mews, you are at the center of the information. You choose the articles you want to read. Thus, your newsfeed and constantly updated according to your preferences.
</ P>

<p class = 'center-align'> How to connect to Mews? </ p>

<p style = 'text-align: justify'> You already have a Mews account
    If you already have an account on Mews, just click on the 'Connect me' button at the top right. You must then enter your username and password in the fields provided for this purpose.
You do not have a Mews account
    If you do not have an account on Mews, just click on the 'Register' button. More information will then be requested such as your name, first name, email address and password. An email will be sent to you to confirm the creation of your account.
</ P>


<p class = 'center-align'> How do I edit my news feed? </ p>

<p style = 'text-align: justify'>
    In order to modify your newsfeed, you are invited to click on the gear. At the click of it, you can activate or deactivate a stream by clicking on the button to the right of the name of the stream.
    It also indicates which category and which language a flow comes from.
</ P>

<p class = 'center-align'> I can not remember my credentials, allowing me to login </ p>

<p style = 'text-align: justify'>
If you do not remember your credentials, you will be asked to enter your email address with which you have registered. Then an email from: wearemews@hotmail.com will be sent to you to remind you of your password.
</ P>

<p class = 'center-align'> Did you notice abnormal operation? </ p>

<p style = 'text-align: justify'>
Despite the constant updates of the site, it is possible that a small dysfunction intervenes. If you notice any problem or malfunction, do not hesitate to report it to the following address: wearemews@hotmail.com. All your returns and reports will be very useful to us to improve our services.
</ P>

<p class = 'center-align'> Did you notice abnormal operation? </ p>

<p style = 'text-align: justify'>
Despite the constant updates of the site, it is possible that a small dysfunction intervenes. If you notice any problem or malfunction, do not hesitate to report it to the following address: wearemews@hotmail.com. All your returns and reports will be very useful to us to improve our services.
</ P>

<p class = 'center-align'> I want to delete my account </ p>

<p style = 'text-align: justify'>
If you wish to permanently delete your account, you must send an email to the following address: wearemews@hotmail.com. A confirmation will be sent almost immediately to the email address linked to your account. </ P>");

//mentions legales

define("_TEXTEMENTION","<p style = 'text-align: justify'> In accordance with the provisions of Articles 6-III and 19 of Law No. 2004-575 of 21 June 2004 on Confidence in the Digital Economy, known as LCEN, we bring to the attention of knowledge of users and visitors to the site: <a href='http://www.mews.com' target='_blank'> www.mews.com </a> the following information: </ p>

<p style = 'text-align: justify'> <strong> 1. Legal information: </ strong> </ p>

<p style = 'text-align: justify'> Owner status: <strong> individual </ strong> <br />
The owner is: <strong> Mews </ strong> <br />
Owner's postal address: <strong> 1 rue Chablis, 93000 Bobigny </ strong> <br />
The number of the owner is: <strong> 01 49 40 30 00 </ strong> <br />
 <br />
The creator of the site is: <strong> Angélique Souvant & Laurine Lafontaine </ strong> <br />
The person responsible for the publication is: <strong> Sophia Hamiteche </ strong> <br />
Contact the publisher: <strong> wearemews@hotmail.com </ strong> <br />
The publisher is a <strong> physical person </ strong> <br />
<br />
The Webmaster is: <strong> Laurine Lafontaine </ strong> <br />
Contact the Webmaster: <strong> <a href='mailto:wearemews@hotmail.com?subject=Contact from the legal mentions via the site www.mews.com'> wearemews@hotmail.com </a> < / strong> <br />
The host of the site is: <strong> 1 & 1 INTERGEST SA 7 PLACE OF THE STATION 57200 SARREGUEMINES </ strong> <br />

Information on the <a href='https://editioneo.com/formalites/declaration-cnil' target='_blank'> CNIL statement </a> </ p>

<p style = 'text-align: justify'> </ p>

<p style = 'text-align: justify'> <strong> 2. Presentation and principle: </ strong> </ p>

<p style = 'text-align: justify'> Is hereinafter referred to as <strong> User </ strong>, any user logging in and using the above named site: <a href = 'http: //www.mews. com 'target =' _ blank '> www.mews.com </a>. <br />
The <strong> www.mews.com </ strong> <strong> </ strong> site groups together a set of services, in the state, made available to users. It is specified here that they must remain courteous and show good faith to both users and the webmaster of the site www.mews.com. The website www.mews.com is updated regularly by Jean Claude. <br />
Company Mews endeavors to provide the most accurate information on www.mews.com (subject to changes made since it was posted), but can not guarantee the accuracy, completeness and timeliness of the information. on its website, whether by its own doing or by third-party partners providing it with this information. As a result, the user acknowledges using this information (indicative, non-exhaustive and subject to change) under his exclusive responsibility. </ P>

<p style = 'text-align: justify'> </ p>

<p style = 'text-align: justify'> <strong> 3. Accessibility: </ strong> <br />
<br />
The site www.mews.com is in principle accessible to the users 24 / 24h, 7 / 7d, except interruption, programmed or not, for the needs of its maintenance or in case of force majeure. In case of impossibility of access to the service, www.mews.com undertakes to do its utmost to restore access to the service and will then endeavor to communicate to users before the dates and times of the intervention. Being subject to an obligation of means, www.mews.com can not be held responsible for any damage, whatever its nature, resulting from unavailability of the service. </ P>

<p style = 'text-align: justify'> </ p>

<p style = 'text-align: justify'> <strong> 4. Intellectual property: </ strong> </ p>

<p style = 'text-align: justify'> <br />
Company Mews is the exclusive owner of all the intellectual property rights or holds the rights of use on all the elements accessible on the site, as much on the structure as on the texts, images, graphics, logo, icons, sounds, software ... br />
Any total or partial reproduction of the site www.mews.com, representation, modification, publication, total or partial adaptation of any of these elements, whatever the means or process used, is prohibited, except with the prior written permission of Company Mews, owner of the site by email: wearemews@hotmail.com, failing which it will be considered as constituting an infringement and liable to prosecution in accordance with the provisions of articles L.335-2 and following of the Intellectual Property Code. </ p>

<p style = 'text-align: justify'> <br />
<Strong> 5. Hypertext links and cookies: </ strong> <br />
<br />
The site www.mews.com contains a number of hypertext links to other sites (partners, information ...) set up with the authorization of Company Mews. However, Company Mews does not have the possibility to check all the contents of the sites thus visited and thus declines all responsibility of this fact when to the possible risks of illicit contents. <br />
The user is informed that during his visits to the site www.mews.com, one or more cookies may be automatically installed on his computer via his browser. A cookie is a block of data that does not identify the user, but that records information relating to the navigation of it on the site. <br />
The setting of the browser software makes it possible to inform of the presence of a cookie and possibly to refuse it in the manner described at the following address: <a href='http://www.cnil.fr'> www.cnil .com </a>. However, the user can configure the browser on his computer to refuse the installation of cookies, knowing that the refusal to install a cookie may result in the inability to access certain services. For any cookie blocking, type in your search engine: blocking cookies in IE or firefox and follow the instructions according to your version. </ P>

<p style = 'text-align: justify'> <br />
<Strong> 6. Protection of property and people - management of personal data: </ strong> <br />
<br />
In France, personal data are protected in particular by the law n ° 78-87 of January 6th, 1978, the law n ° 2004-801 of August 6th, 2004, the article L. 226-13 of the Penal Code and the European directive of the October 24, 1995. </ P>

<p style = 'text-align: justify'> On the site www.mews.com, Company Mews does not collect personal information (according to the article 4 law n ° 78-17 of January 06th, 1978) relating to the user only for the need of certain services offered by the site www.mews.com. The user provides this information with full knowledge of the facts, in particular when he proceeds to input them himself. It is then specified to the user of the site www.mews.com the obligation or not to provide this information. <br />
In accordance with the provisions of Article 38 et seq. Of Law 78-17 of 6 January 1978 relating to data, files and freedoms, all users have the right of access, rectification, cancellation and opposition. to the personal data concerning him. To exercise this right, send your request to www.mews.com by email: <strong> <a href = 'mailto: wearemews@hotmail.com? Subject = Contact from the legal mentions via the website www. mews.com '> wearemews@hotmail.com </a> </ strong> or in writing duly signed, accompanied by a copy of the identity card with signature of the holder of the room, specifying the address to which the answer must be sent. </ p>

<p style = 'text-align: justify'> No personal information of the user of the site www.mews.com is published without the knowledge of the user, exchanged, transferred, assigned or sold on any support to others. Only the assumption of redemption of the site www.mews.com and its rights authorizes Company Mews to transmit such information to the prospective purchaser who would in turn be held to the same obligation to store and modify data with respect to of the user of the site www.mews.com. <br />
The site www.mews.com is declared to the CNIL under the number 033256847. </ P>

<p style = 'text-align: justify'> Databases are protected by the provisions of the Act of 1 July 1998 transposing Directive 96/9 of 11 March 1996 on the legal protection of databases. </ p> p>");

//CONDITION utilisation
define("_COND","Terms of use");
define("_TEXTECOND","<p style = 'text-align: justify'> Please read the terms and conditions of use carefully before using <a href = 'http: //international.iut-bobigny.univ-paris13.fr/iobc2018/mews/ '> http://international.iut-bobigny.univ-paris13.fr/iobc2018/mews/ </a>
By accessing and using the site, you signify your agreement to these terms and conditions in their entirety. </ P>

<p style = 'text-align: justify'> The site accessible by the following url: <a href='http://international.iut-bobigny.univ-paris13.fr/iobc2018/mews/'> http: //international.iut-bobigny.univ-paris13.fr/iobc2018/mews/ </a> is operated in compliance with French law, which implies the full and complete acceptance of the general conditions of use described below . These conditions of use are likely
Modified or completed at any time, users of the Mews site are invited to consult them regularly. Mews can not be held responsible in any way for misuse of the service. This site is normally accessible to users at any time. Interruption due to technical maintenance
However, it may be decided by Mews, who will then endeavor to communicate to users the dates and times of the intervention. Mews strives to provide the site with as accurate information as possible. However, he can not be held responsible for omissions, inaccuracies and deficiencies in the update,
whether by its own doing or by the third party partners providing it with this information. </ p>
");
define("_PRECAUTION","Precautions of use");
define("_TEXTEPRECAUTION","<p style = 'text-align: justify'> It is therefore your responsibility to take the necessary precautions to ensure that what you choose to use is not tainted with errors or even destructive elements. such as viruses, trojans ..
This site is offered in HTML5, CSS3, JavaScript and PHP languages. For a better user experience, we recommend using modern browsers like Safari, Firefox, Chrome.
</ P>");


?>
