<?php

// NAVIGATION
define("_FIL","Емисия за новини");
define("_FILOF","Новини за ");
define("_FAV","любим");
define("_MYFAV","любимите ми");
define("_INSCRIPTION","регистрация");
define("_CONNEXION","Влезте,");
define("_DECONNEXION","Изход");

//PRESENTATION PAGE 1
define("_PRESENTATION","представяне");
define("_TEXTEPRESENTATION","Mews е сайт, който ви позволява да разполагате във вашите новинарски емисии с най-новите списания и най-новите новини.
           <br/> Mews е разработен от международния екип на MTeam.
           9 млади хора страстно към интернет и новините.
           Графичните дизайнери, уеб разработчиците и комуникаторите работят заедно, за да ви предложат качествена услуга.
           Динамичността, креативността и качеството са в основата на нашия проект!");
define("_DESCRIPTIONUN","Новини в реално време");
define("_TEXTEDESCRIPTIONUN","Няма повече търсене на новини от различни сайтове
С Mews можете да следите новините в реално време и навсякъде по света. По същия начин едно просто търсене може да ви помогне да намерите статията, която търсите.
");
define("_DESCRIPTIONDEUX","Персонализиране на емисията за новиниs");
define("_TEXTEDESCRIPTIONDEUX","Уморихте ли се да видите информация, която не ви е полезна? Благодарение на настройките можете да избирате темите, които ви интересуват, за да имате само тази информация във вашия информационен бюлетин.
");
define("_DESCRIPTIONTROIS","Най-популярните статии");
define("_TEXTEDESCRIPTIONTROIS","Благодарение на любимия инструмент можете да видите информацията, предоставена от различни потребители, ще ви позволи да видите най-модерните новини!");


define("_LEGENDVIDEO","Целта на видеото ни е да популяризираме нашия уеб сайт, да го направим видим за широката общественост. В този видеоклип обясняваме, че живеем в свят, пълен с информация и че по-голямата част от информацията, която консултираме, не ни интересува, затова проектът Mews оживява с този уебсайт, можете да избирате темите, които Ви интересуваме, за да имаме само информация за темите, които ни интересуват.
");
define("_REVUE","Преглед на пресата");
define("_TEXTEREVUE","Днес е 8 март 2018 г., Международният ден на правата на жените. Това е възможност за нас, редакторите на Mews, да направят бързо световно турне.");
define("_LIRESUITE","Прочетете повече (изтеглите PDF)");


// REUTILISABLE
define("_ANNEXE","Прикачени");
define("_BOOFOFSPEC","спецификации");
define("_CHARTE","Графичен чартър");
define("_SOCIAL","Социални мрежи");
define("_LINK","връзки");
define("_ABOUT","заs");
define("_FAQ","Отговори");
define("_MENTION","Правна информация");
define("_USE","Условия за ползване");
define("_PRENOM","СОБСТВЕНО ИМЕ");
define("_NOM","ИМЕ");
define("_DATENAISSANCE","ДАТА НА РАЖДАНЕE");
define("_SEXE","SEXE");
define("_FEMME","жена");
define("_HOMME","мъжe");
define("_MAIL","АДРЕС НА ПОЩА");
define("_CMAIL","Потвърдете имейл адресаl");
define("_MDP","ПАРОЛА");
define("_CMDP","Потвърдете паролата");
define("_CINSCRIPTION","Регистрирам се");
define("_FMDP","(Забравена парола)");
define("_CCONEXION","Влизам");
define("_PARAM","настройки");
define("_LISTFLUX","Влизам");
define("_MERCI","благодаря");
define("_KWORD","Ключови думи");
define("_SKWORD","Ключови думи (разделени със запетаи)es)");
define("_TREND","Топ статии");


// APROPOS

define("_TEXTEABOUT","Създадена през 2018 г., Mews е специализирана платформа за информация. Всеки ден избираме най-добрата информация за всички новинарски теми: спорт, бизнес, наука, хора и много други!

Време е да революционизирате света на информацията, като Mews, избирате източниците си и вашите субекти.

На Меус сте в центъра на информацията!");

define("_QUI","Кои сме ние?");
define("_TEXTEQUI","Mews е разработен от международния отбор MTeam. 9 млади хора страстно към интернет и новините. Графичните дизайнери, уеб разработчиците и комуникаторите работят заедно, за да ви предложат качествено обслужване.
Динамичността, креативността и качеството са в основата на нашия проект!");

//FAQ
define("_QMEWS","Какво представлява Mews? ?");
define("_TEXTFAQ","<p style = 'text-align: justify'> Mews е информационна платформа, създадена през 2018 г. Тя обединява голям брой статии по всички текущи теми. С Меус сте в центъра на информацията. Вие избирате статиите, които искате да прочетете. По този начин вашият newsfeed и постоянно се актуализира според вашите предпочитания.
</ P>

<p class = 'center-align'> Как да се свържа с Mews? </ p>

<p style = 'text-align: justify'> Вече имате профил в Mews
    Ако вече имате профил в Mews, просто кликнете върху бутона 'Свързване с мен' горе вдясно. След това трябва да въведете потребителското си име и парола в полетата, предвидени за тази цел.
Нямате профил в Mews
    Ако нямате профил в Mews, просто кликнете върху бутона 'Регистриране'. След това ще бъде поискана допълнителна информация, като вашето име, собствено име, имейл адрес и парола. Ще ви бъде изпратен имейл, за да потвърдите създаването на профила си.
</ P>


<p class = 'center-align'> Как да редактирам информационната си емисия? </ p>

<p style = 'text-align: justify'>
    За да промените своя информационен бюлетин, вие сте поканени да кликнете върху устройството. При натискането му можете да активирате или деактивирате поток, като кликнете върху бутона отдясно на името на потока.
    Той също така посочва от коя категория и от кой език идва потокът.
</ P>

<p class = 'center-align'> Не мога да си спомня моите акредитиви, което ми позволява да вляза в профила си </ p>

<p style = 'text-align: justify'>
Ако не помните вашите пълномощия, ще бъдете помолени да въведете вашия имейл адрес, с който сте се регистрирали. След това ще Ви бъде изпратен имейл от: wearemews@hotmail.com, за да ви напомним за паролата си.
</ P>

<p class = 'center-align'> Забелязали ли сте ненормална работа? </ p>

<p style = 'text-align: justify'>
Въпреки постоянните актуализации на сайта, възможно е да се намеси малка дисфункция. Ако забележите някакъв проблем или неизправност, не се колебайте да го съобщите на следния адрес: wearemews@hotmail.com. Всички ваши връщания и отчети ще бъдат много полезни за нас, за да подобрим услугите си.
</ P>

<p class = 'center-align'> Забелязали ли сте ненормална работа? </ p>

<p style = 'text-align: justify'>
Въпреки постоянните актуализации на сайта, възможно е да се намеси малка дисфункция. Ако забележите някакъв проблем или неизправност, не се колебайте да го съобщите на следния адрес: wearemews@hotmail.com. Всички ваши връщания и отчети ще бъдат много полезни за нас, за да подобрим услугите си.
</ P>

<p class = 'center-align'> Искам да изтрия профила си </ p>

<p style = 'text-align: justify'>
Ако искате да изтриете за постоянно профила си, трябва да изпратите имейл до следния адрес: wearemews@hotmail.com. Потвърждение ще бъде изпратено почти веднага до имейл адреса, свързан с профила ви. </ P>
<p class = 'center-align'> Mews е информационна платформа, създадена през 2018 г. Тя о и и и и ...................... С мене сте в центъра на информацията. Вие избирате статиите, които искате да прочетете. По този начин вашият новинарски поток и постоянно се актуализира според вашите предпочитания.
</ P>
<p class = 'center-align'> Как да се свържа с Mews? </ p>

<p style = 'text-align: justify'> Вече имате профил в Mews
    Ако вече имате профил в Mews, просто кликнете върху бутона 'Свързване с мен' горе вдясно. След това трябва да въведете потребителското си име и парола в полетата, предвидени за тази цел.
Нямате профил в Mews
    Ако нямате профил в Mews, просто кликнете върху бутона 'Регистриране'. След това ще бъде поискана допълнителна информация, като вашето име, собствено име, имейл адрес и парола. Ще ви бъде изпратен имейл, за да потвърдите създаването на профила си.
</ P>


<p class = 'center-align'> Как да редактирам информационната си емисия? </ p>

<p style = 'text-align: justify'>
    За да промените своя информационен бюлетин, вие сте поканени да кликнете върху устройството. При натискането му можете да активирате или деактивирате поток, като кликнете върху бутона отдясно на името на потока.
    Той също така посочва от коя категория и от кой език идва потокът.
</ P>

<p class = 'center-align'> Не мога да си спомня моите акредитиви, което ми позволява да вляза в профила си </ p>

<p style = 'text-align: justify'>
Ако не помните вашите пълномощия, ще бъдете помолени да въведете вашия имейл адрес, с който сте се регистрирали. След това ще Ви бъде изпратен имейл от: wearemews@hotmail.com, за да ви напомним за паролата си.
</ P>

<p class = 'center-align'> Забелязали ли сте ненормална работа? </ p>

<p style = 'text-align: justify'>
Въпреки постоянните актуализации на сайта, възможно е да се намеси малка дисфункция. Ако забележите някакъв проблем или неизправност, не се колебайте да го съобщите на следния адрес: wearemews@hotmail.com. Всички ваши връщания и отчети ще бъдат много полезни за нас, за да подобрим услугите си.
</ P>

<p class = 'center-align'> Забелязали ли сте ненормална работа? </ p>

<p style = 'text-align: justify'>
Въпреки постоянните актуализации на сайта, възможно е да се намеси малка дисфункция. Ако забележите някакъв проблем или неизправност, не се колебайте да го съобщите на следния адрес: wearemews@hotmail.com. Всички ваши връщания и отчети ще бъдат много полезни за нас, за да подобрим услугите си.
</ P>

<p class = 'center-align'> Искам да изтрия профила си </ p>

<p style = 'text-align: justify'>
Ако искате да изтриете за постоянно профила си, трябва да изпратите имейл до следния адрес: wearemews@hotmail.com. Потвърждение ще бъде изпратено почти веднага до имейл адреса, свързан с профила ви. </ P>
<p style = 'text-align: justify'> Mews e informatsionna platforma, sŭzdadena prez 2018 g. Tya obedinyava golyam broĭ statii po vsichki tekushti temi. S Meus ste v tsentŭra na informatsiyata. Vie izbirate statiite, koito iskate da prochetete. Po tozi nachin vashiyat newsfeed i postoyanno se aktualizira spored vashite predpochitaniya.
</ P>

<p class = 'center-align'> Kak da se svŭrzha s Mews? </ p>

<p style = 'text-align: justify'> Veche imate profil v Mews
    Ako veche imate profil v Mews, prosto kliknete vŭrkhu butona 'Svŭrzvane s men' gore vdyasno. Sled tova tryabva da vŭvedete potrebitelskoto si ime i parola v poletata, predvideni za tazi tsel.
Nyamate profil v Mews
    Ako nyamate profil v Mews, prosto kliknete vŭrkhu butona 'Registrirane'. Sled tova shte bŭde poiskana dopŭlnitelna informatsiya, kato vasheto ime, sobstveno ime, imeĭl adres i parola. Shte vi bŭde izpraten imeĭl, za da potvŭrdite sŭzdavaneto na profila si.
</ P>


<p class = 'center-align'> Kak da redaktiram informatsionnata si emisiya? </ p>

<p style = 'text-align: justify'>
    Za da promenite svoya informatsionen byuletin, vie ste pokaneni da kliknete vŭrkhu ustroĭstvoto. Pri natiskaneto mu mozhete da aktivirate ili deaktivirate potok, kato kliknete vŭrkhu butona otdyasno na imeto na potoka.
    Toĭ sŭshto taka posochva ot koya kategoriya i ot koĭ ezik idva potokŭt.
</ P>

<p class = 'center-align'> Ne moga da si spomnya moite akreditivi, koeto mi pozvolyava da vlyaza v profila si </ p>

<p style = 'text-align: justify'>
Ako ne pomnite vashite pŭlnomoshtiya, shte bŭdete pomoleni da vŭvedete vashiya imeĭl adres, s koĭto ste se registrirali. Sled tova shte Vi bŭde izpraten imeĭl ot: wearemews@hotmail.com, za da vi napomnim za parolata si.
</ P>

<p class = 'center-align'> Zabelyazali li ste nenormalna rabota? </ p>

<p style = 'text-align: justify'>
Vŭpreki postoyannite aktualizatsii na saĭta, vŭzmozhno e da se namesi malka disfunktsiya. Ako zabelezhite nyakakŭv problem ili neizpravnost, ne se kolebaĭte da go sŭobshtite na sledniya adres: wearemews@hotmail.com. Vsichki vashi vrŭshtaniya i otcheti shte bŭdat mnogo polezni za nas, za da podobrim uslugite si.
</ P>

<p class = 'center-align'> Zabelyazali li ste nenormalna rabota? </ p>

<p style = 'text-align: justify'>
Vŭpreki postoyannite aktualizatsii na saĭta, vŭzmozhno e da se namesi malka disfunktsiya. Ako zabelezhite nyakakŭv problem ili neizpravnost, ne se kolebaĭte da go sŭobshtite na sledniya adres: wearemews@hotmail.com. Vsichki vashi vrŭshtaniya i otcheti shte bŭdat mnogo polezni za nas, za da podobrim uslugite si.
</ P>

<p class = 'center-align'> Iskam da iztriya profila si </ p>

<p style = 'text-align: justify'>
Ako iskate da iztriete za postoyanno profila si, tryabva da izpratite imeĭl do sledniya adres: wearemews@hotmail.com. Potvŭrzhdenie shte bŭde izprateno pochti vednaga do imeĭl adresa, svŭrzan s profila vi. </ P>
");

//mentions legales

define("_TEXTEMENTION","В съответствие с разпоредбите на членове 6-III и 19 от Закон № 2004-575 от 21 юни 2004 г. относно доверието в цифровата икономика, известен като LCEN, ние привличаме вниманието на познаване на потребителите и посетителите на сайта: <a href='http://www.mews.com' target='_blank'> www.mews.com </a> следната информация: </ p>

<p style = 'text-align: justify'> <strong> 1. Правна информация: </ strong> </ p>

<p style = 'text-align: justify'> Състояние на собственика: <strong> индивидуален </ strong> <br />
Собственикът е: <strong> Mews </ strong> <br />
Пощенски адрес на собственика: <strong> 1 rue Chablis, 93000 Bobigny </ strong> <br />
Номерът на собственика е: <strong> 01 49 40 30 00 </ strong> <br />
 <br />
Създателят на сайта е: <strong> Angélique Souvant & Laurine Lafontaine </ strong> <br />
Лицето, отговорно за публикацията, е: <strong> Sophia Hamiteche </ strong> <br />
Свържете се с издателя: <strong> wearemews@hotmail.com </ strong> <br />
Издателят е <strong> физическо лице </ strong> <br />
<br />
Уеб администраторът е: <strong> Laurine Lafontaine </ strong> <br />
Свържете се с уеб администратора: <strong> <a href='mailto:wearemews@hotmail.com?subject=Свържете се с правните съобщения чрез сайта www.mews.com'> wearemews@hotmail.com </a> < / strong> <br />
Домакин на сайта е: <strong> 1 & 1 INTERGEST SA 7 МЯСТО НА СТАНЦИЯТА 57200 SARREGUEMINES </ strong> <br />

Информация относно <a href='https://editioneo.com/formalites/declaration-cnil' target='_blank'> изявлението CNIL </a> </ p>

<p style = 'text-align: justify'> </ p>

<p style = 'text-align: justify'> <strong> 2. Представяне и принцип: </ strong> </ p>

<p style = 'text-align: justify'> По-долу се нарича <strong> Потребител </ strong> всеки потребител, който влезе в профила си и използва горепосочения сайт: <a href = 'http: //www.mews. com 'target =' _ blank '> www.mews.com </a>
Сайтът <strong> www.mews.com </ strong> <strong> </ strong> обединява набор от услуги в държавата, предоставени на потребителите. Тук е посочено, че те трябва да останат любезни и да покажат добросъвестност както на потребителите, така и на уебмастъра на сайта www.mews.com. Сайтът www.mews.com се актуализира редовно от Жан Клод. <br />
Дружеството Mews се стреми да предостави най-точната информация на www.mews.com (в зависимост от промените, направени след публикуването му), но не може да гарантира точността, пълнотата и своевременността на информацията. на своя уебсайт, независимо дали чрез собствените си действия или от трети страни партньори, които му предоставят тази информация. В резултат на това потребителят признава използването на тази информация (индикативна, неизчерпателна и подлежи на промяна) под негова изключителна отговорност. </ P>

<p style = 'text-align: justify'> </ p>

<p style = 'text-align: justify'> <strong> 3. Достъпност: </ strong> <br />
<br />
Сайтът www.mews.com е по принцип достъпен за потребителите 24 / 24h, 7 / 7d, с изключение на прекъсването, програмирано или не, за целите на поддръжката му или в случай на непреодолима сила. В случай на невъзможност за достъп до услугата, www.mews.com се ангажира да направи всичко възможно, за да възстанови достъпа до услугата и след това ще се опита да съобщи на потребителите преди датите и часовете на интервенцията. Като обект на задължение за средства, www.mews.com не може да бъде държана отговорна за каквито и да било вреди, независимо от естеството им, в резултат на липсата на услуга. </ P>

<p style = 'text-align: justify'> </ p>

<p style = 'text-align: justify'> <strong> 4. Интелектуална собственост: </ strong> </ p>

<p style = 'text-align: justify'> <br />
Фирмата Mews е изключителен собственик на всички права върху интелектуална собственост или притежава правата за ползване върху всички елементи, достъпни на сайта, както върху структурата, така и върху текстове, изображения, графики, лого, икони, звуци, софтуер ... br />
Всяко пълно или частично възпроизвеждане на сайта www.mews.com, представяне, промяна, публикуване, пълно или частично адаптиране на който и да е от тези елементи, независимо от използваните средства или процес, е забранено, освен с предварителното писмено разрешение на Дружеството Mews, собственик на сайта по електронна поща: wearemews@hotmail.com, в противен случай ще се счита, че представлява нарушение и може да бъде преследвано в съответствие с разпоредбите на членове L.335-2 и следващите от Кодекса за интелектуална собственост. </ P>

<p style = 'text-align: justify'> <br />
<Strong> 5. Хипертекстови връзки и бисквитки': </ strong> <br />
<br />
Сайтът www.mews.com съдържа редица хипертекстови връзки към други сайтове (партньори, информация ...), създадени с разрешението на Company Mews. Дружеството Mews обаче няма възможност да провери цялото съдържание на посещаваните по този начин сайтове и по този начин отхвърля цялата отговорност за този факт, когато става дума за възможните рискове от незаконно съдържание. <br />
Потребителят е
");

//CONDITION utilisation
define("_COND","Условия за ползване");
define("_TEXTECOND","<p class = 'center-align'> Моля, прочетете условията за ползване, преди да използвате сайта <един HREF = 'HTTP: //international.iut-bobigny.univ-paris13.fr/iobc2018/mews/ '> http://international.iut-bobigny.univ-paris13.fr/iobc2018/mews/ </a>
С достъпа до и използването на сайта вие изразявате съгласието си с тези условия в тяхната цялост. </ P>

<p class = 'center-align'> Сайтът достъпни чрез следния адрес: <a href='http://international.iut-bobigny.univ-paris13.fr/iobc2018/mews/'> HTTP: //international.iut-bobigny.univ-paris13.fr/iobc2018/mews/ </a> се експлоатира в съответствие с френското законодателство, което предполага пълно приемане на общите условия описани по-долу, използвайки , Тези условия на употреба са вероятни
Модифицирани или завършени по всяко време, потребителите на сайта Mews са поканени да се консултират редовно с тях. Mews не може да бъде държан отговорен по никакъв начин за злоупотреба с услугата. Този сайт обикновено е достъпен за потребителите по всяко време. Прекъсване поради техническа поддръжка
Обаче, може да бъде решено от Mews, които след това ще се опитат да съобщят на потребителите датите и часовете на интервенцията. Mews се стреми да предостави на сайта възможно най-точна информация. Той обаче не може да носи отговорност за пропуски, неточности и недостатъци в актуализацията,
независимо дали чрез собствените си действия или от третите партньори, които му предоставят тази информация. </ p>
");
define("_PRECAUTION","Предпазни мерки при употреба");
define("_TEXTEPRECAUTION","<p style = 'text-align: justify'> Следователно, ваша отговорност е да вземете необходимите предпазни мерки, за да сте сигурни, че това, което изберете да използвате, не е заклещено с грешки или дори разрушителни елементи. като вируси, троянци.
Този сайт се предлага в езици HTML5, CSS3, JavaScript и PHP. За по-добра практическа работа на потребителите ви препоръчваме да използвате съвременни браузъри като Safari, Firefox, Chrome.
</ P>");


?>
